* One liners palieku worde, ten jie strukturizuoti bsk
* noliferis

kai dirbi del saves o ne del kitos kompanijos kokios nors, tuomet atrodo kad
kuo daugiau laiko pats skirsi tai veiklai, tuo geriau tau seksis. jei dirbi
kitoje imoneje, atidirbi kiek reikia ir rami galva buna... isklausai mytinga
kaip onute ir tuoemet eini atsipalaiduoti, galvos nekvarsindamas ka veliau
veiksi. kai dirbu sau, belenkiek dalyku reikia padaryti, laiko irgi daug yra,
tai atrodo kodel gi jo neleisti atlikineti tom veiklom.... kai dirbu statybose,
laikrasciai, cobe, indai... visuomet as tik noriu pabegti is darbo ir leisti
sau laika. ane? kai dirbu del saves - photography, coding, revit... as
nolifinu. kaip cia iseina?

* nueini i kindle per desktop app, paspaudi "Your Notes and Highlights" ir ten
bus ivairiu quotes kuriu gal but nesi niekur pasirases. Persiziurek ir
susirasyk.

* last words of steve jobs

Paskutiniai milijardieriaus Steve Jobs, mirusio 56-erių, žodžiai:
„Aš pasiekiau sėkmės viršūnę versle. Kitų žmonių akyse mano gyvenimas yra sėkmė.
Tačiau, neskaitant darbo, džiaugsmo turėjau nedaug.
Dienos pabaigoje turtas yra tik faktas, prie kurio pripratau.
Dabar, gulėdamas ant ligoninės lovos ir prisimindamas visą gyvenimą  suprantu, kad visas pripažinimas ir turtas, kuriuo taip didžiavausi, išblėso ir tapo beprasmis artėjančios mirties akivaizdoje.
Gali samdyti žmogų, kuris vairuos tavo automobilį arba uždirbs tau pinigus, bet negali pasamdyti žmogaus, kuris sirgtų ir mirtų dėl tavęs.
Pamestus materialius daiktus galima surasti. Bet yra vienas dalykas, kurio neįmanoma ir vėl rasti, kai jis prarandamas: tai yra gyvenimas.
Kad ir kokiame gyvenimo etape šiuo metu esame, ateis diena, kai uždanga nusileis.
Mylėkite savo šeimą, sutuoktinį, vaikus ir draugus...
Elkitės su jais teisingai.
Branginkite juos.
Kai tampame vyresni ir išmintingesni, pamažu suprantame, kad nesvarbu, ar segime $300 ar 30$ kainuojantį laikrodį abu rodo tą patį laiką.
Nesvarbu, ar turime 300$ ar 30$ kainuojančią piniginę ar rankinę, suma joje yra tokia pati.
Nesvarbu, ar važiuojame 150 000$ ar 30 000$ kainuojančiu automobiliu, kelias ir atstumas yra vienodi ir mes pasieksime tą patį kelionės tikslą.
Nesvarbu, ar išgertume 1000 $, ar 10 $ kainuojantį vyno butelį, pagirios bus tos pačios.
Nesvarbu, ar namas, kuriame gyvename yra 100 ar 1000 kvadratinių metrų dydžio, vienatvė yra ta pati.
Suprasite, kad jūsų tikroji vidinė laimė kyla ne iš materialių šio pasaulio dalykų.
Nesvarbu, ar keliaujate pirma ar ekonomine klase, jei lėktuvas dūžta jūs leisitės juo žemyn...
Todėl tikiuosi suprasite, kad tikroji laimė yra tai, kad turite draugų, brolių ir sesių, su kuriais diskutuojate, juokiatės, kalbatės, dainuojate, kalbatės apie Šiaurės-pietryčius ar dangų ir žemę. Tai yra tikroji laimė!!!
Neginčijamas gyvenimo faktas ir patarimas:
neauklėkite savo vaikų būti turtingais, ugdykite juos būti laimingais.
Kai jie užaugs, jie žinos daiktų vertę, o ne kainą. "
* Julytes žinutė iš Instagramo su 4 auksinem tsisyklem
* Black mirror
** 2

Issitryne daug..

ko. zmogus atejo su ideja nusižudyti, išsakyti visą tiesą, akivaizdžia visiem tiesa ir jis buvo sulygintas su žeme... kad nedarytum samisio. netikėtumas? privertė juos manyti, jog tai bus jiem geriau, kad visi norėtų būti ju vietoje.

darbe problemos? mes tau duosim daugiau materialių dalykų. namą, mašina, alga, tu tik būk ramus. žmogus galvojo oh okey, aš nekenčiau savo darbo, bet gal būt dar galėčiau čia pabūti.

 even though I had these realizations now - there is nothing I can do about it. i will get up tomorrow, go to work, come back from work into my family that I don't like and etc etc, be part of the system because there is no way out.

Pzdc


2021.04.08 update

What happens when you see a super strong quote that affects you? At first you think your life will turn around, but eventually you get back on the track because you are kept so busy and there is no time for any kind of improvement or major change. Its a fucking great way for someone to control humanity like this. Just as the guy in this episode, said all this stuff, true stuff, straight to peoples faces and what they ended up doing or changing? Nothing. The 3 people that are auditing new ideas put the fire down quick by realizing the potential threats that are in this persons mind. Wow man… realized all of this while watching this video - https://www.youtube.com/watch?v=kCM_CODi4vM
** 3

Nenori tureti chipo galvoje? Na, mum reikia, kad tu ji turetum, nes kaip mes zinosim, ar tu svarus before you step in the plane. How we will check the memory before we order a job, maybe you are a serial killer.

The same way the program now scans if you have a mask on your face, the same way it will scan if you have met any wanted people or you did some activity which is illegal.

Will make you think that you NEED it, will find ways to make you believe. Then it's not going to be strange to have it but strange NOT to have it.




p


Bitutes season 3 5-6 serija

Depends whether stuff is in good or bad hands.
Is kur tiek neapykantos pas zmones. Sutinki ji, normalaus zmogus, bet katik keitesi ir linkejo mirties.

Viskas sujungta, labai lengva isnaudoti…
** 4 sezonas sudo visus



natural protection against doing bad things. by nature - feeling guilt and etc


in the future - oh we can check your memories, you wont be able to run away.

now - by nature design - kaip programs, kaip atsargine priemone nedsrymui blogu dalyku - kaltes jausmas.

moteris prisedo ant tuliko, negerai jautesi that she just killed a man. she felt like shit. that's her byproduct.

* Bob marley

tell them about it, knowing they will share in your excitement. They
are not embarrassed to cry with you when you are hurting or laugh with
you when you make a fool of yourself. Never do they hurt your feelings
or make you feel like you are not good enough, but rather they build
you up and show you the things about yourself that make you special
and even beautiful. There is never any pressure, jealousy or
competition but only a quiet calmness when they are around. You can be
yourself and not worry about what they will think of you because they
love you for who you are. The things that seem insignificant to most
people such as a note, song or walk become invaluable treasures kept
safe in your heart to cherish forever. Memories of your childhood come
back and are so clear and vivid it’s like being young again. Colours
seem brighter and more brilliant. Laughter seems part of daily life
where before it was infrequent or didn’t exist at all. A phone call or
two during the day helps to get you through a long day’s work and
always brings a smile to your face. In their presence, there’s no need
for continuous conversation, but you find you’re quite content in just
having them nearby. Things that never interested you before become
fascinating because you know they are important to this person who is
so special to you. You think of this person on every occasion and in
everything you do. Simple things bring them to mind like a pale blue
sky, gentle wind or even a storm cloud on the horizon. You open your
heart knowing that there’s a chance it may be broken one day and in
opening your heart, you experience a love and joy that you never
dreamed possible. You find that being vulnerable is the only way to
allow your heart to feel true pleasure that’s so real it scares you.
You find strength in knowing you have a true friend and possibly a
soul mate who will remain loyal to the end. Life seems completely
different, exciting and worthwhile. Your only hope and security is in
knowing that they are a part of your life. Bob Marley

* ilgos is gvazdikelis

Tendency Toward Complexity

‘The history of the universe is a history of motion,’ Khader began,
still looking at the boats nodding together like horses in harness.
‘The universe, as we know it, in this one of its many lives, began in
an expansion that was so big, and so fast that we can talk about it,
but we cannot in any truth understand it, or even imagine it. The
scientists call this great expansion the Big Bang, although there was
no explosion, in the sense of a bomb, or something like that. And the
first moments after that great expansion, from the first fractions of
attoseconds, the universe was like a rich soup made out of simple bits
of things.

Those bits were so simple that they were not even atoms yet. As the
universe expanded and cooled down, these very tiny bits of things came
together to make particles. Then the particles came together to make
the first of the atoms. Then the atoms came together to make
molecules. Then the molecules came together to make the first of the
stars. Those first stars went through their cycles, and exploded in a
shower of new atoms. The new atoms came together to make more stars
and planets. All the stuff we are made of came from those dying stars.
We are made out of stars, you and I. Do you agree with me so far?’

'Sure,’ I smiled. ‘I don’t know where you’re going yet, but so far, so
good.’ ‘Precisely!’ he laughed. ‘So far, so good. You can check the
science of what I am saying to you—as a matter of fact, I want you to
check everything that I say, and everything you ever learn from anyone
else.

There are too many variables to know the motivations behind that
particular action at that particular time. Over-analyzing never added
a second to anyone’s life. You’re going to be fine with or without
them. If you have to alter your identity to win them back, then you’re
not really winning anything.

GOLD

“A relationship based on love… is one in which each partner allows the
other to be what he or she chooses, with no expectations and no
demands. It is a simple association of two people who love each other
so much that each would never expect the other to be something that he
or she wouldn’t choose for himself. It is a union of independence,
rather than dependence."

GOLD

Message to Aishwarya - 2020/05/30

"There are two ways. Of "what", I dont know. but I'm torn between
those two so I cns not pick one to live by.

One - EVERYTHING is okay.

other one - I pick and choose. 13:05

"Its the worst. I decided Ill write them down so somewehre and keeo
the one where everything is okay in my mind as a real truth and live
by the second one where I pick and choose.

Irealized something else juts now/ that humans can not live byy the
real truth.

1st truth - EVERYTHING IS OKAY.

It is how it is. Evolution, tendency towards complexity, process,
gradual, right, rpoper, inevitable. Where it grets interesting -
religion - okay. No religion - okay. Spiritual - okay, not spiritual -
okay. variaty, ego formations, nothing wrong, murder - okay, alive -
okay, tragedy - okay, no trageedy - okay. Continuous, never ending
process, learning from itself, developing by own(universe) "mistakes".
Depresssion - okay, alchohol - okay, no self control - okay,no shame -
okay, no goals - okay, no future plans - okay, addict - okay. all are
just labels t labe l things which are done by the things that popped
into exidtence nand gradually developed ego and THAT is also okay.
EVERYTHING, EVERY EMOTION/ACTION is okay.

2nd - CONTROLLING

you are the controller, ruler, master of your actions, thoughts,
behavious, feelings, emotions, reactions, words, moods. cravings,
addictions, surroundings, atitude, future and so on.You live by this
"fake sense of control" when the ego is super strong (which is also
okay according to the 1st truth). It needs control, feels good when
having control over all that is mentioned above. Good example -
buddhist monk or some youtube motivational speaker. Very pleasant
image to look at, ostly admired by the 3rd category, but "laugher
upon" by the 1st. but actually no, 1st is full of understanding,
knowing that everything is okay, it is just different level.

3rd - REACTNG (decided there is a third way.

Category in whihc majority of current population falls in and are
easily manipulated by TV, media, fashion, treds, lluxury items,
offers, shiny things, discounts, newest topics, opinions of others,
actions of others, weather, money.. what else?... life s of others,
government, faily. friends, tastes, feelings, words... (lost train of
thought because I just decuded ill take a pic and send all this to
you, A)/

And so when I say Humans can not live by the first truth is because...
we are humans, man. All of us have thus ego that has evolved from
nothing, it is in each and evey one of us. If you say "I lost my ego"
it just means your ego itself is giving you this feeling, you are very
deep in the 2nd. All we can do is know the truth (1st) and then
because we are on this planet in these surroundings, we have no
choice, but choose between 2nd and 3rd.
