# install the package - `pip install pre-commit`
# write the configuration like below
# possible hooks - https://pre-commit.com/hooks.html
# in my case I am using some pre-commit hooks, some makefile thingies
# run `pre-commit install` - This command installs the pre-commit hook into your .git/hooks/pre-commit so that it will be automatically run before each commit.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: local
    hooks:
      # - id: lint
      #   name: Linting
      #   entry: make lint
      #   language: system
      #   stages: [commit]
      - id: test
        name: Run Tests
        entry: make test
        language: system
        stages: [commit]
