# Generated by Django 5.0.3 on 2024-03-24 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 17, 2, 37, 327571), editable=False),
        ),
    ]
