name: Formatters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
