name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Make
        run: sudo apt-get install make

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          make test

      - name: Generate coverage.txt
        run: |
          coverage report > coverage.txt

      - name: Check if coverage.txt exists
        run: |
          if [ -f "coverage.txt" ]; then
            echo "coverage.txt exists"
          else
            echo "coverage.txt does not exist"
            exit 1
          fi

      - name: View coverage.txt content
        run: |
          cat coverage.txt


      # # Check code if code coverage is more than 90%
      # - name: Check Code Coverage
      #   run: |
      #     coverage report
      #     COVERAGE_THRESHOLD=90
      #     COVERAGE_PERCENT=$(grep -oP '\d+\.\d+%' coverage.txt | tr -d '%')
      #     if (( $(echo "$COVERAGE_PERCENT < $COVERAGE_THRESHOLD" | bc -l) )); then
      #       echo "Code coverage is below $COVERAGE_THRESHOLD% ($COVERAGE_PERCENT%)"
      #       exit 1
      #     fi
      #   shell: bash
