name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Make
        run: sudo apt-get install make

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          make coverage

      # Check code coverage
      - name: Check Code Coverage
        run: |
          COVERAGE_THRESHOLD=90
          COVERAGE_PERCENT=$(grep -oP '\d+\.\d+%' coverage.txt | tr -d '%')
          if (( $(echo "$COVERAGE_PERCENT < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Code coverage is below $COVERAGE_THRESHOLD% ($COVERAGE_PERCENT%)"
            exit 1
          fi
        shell: bash
